name: my_coffee
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  camera: ^0.11.0+2
  image_picker: ^0.8.7+3
  flutter_email_sender: ^6.0.3

dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

  flutter_native_splash: ^2.0.4
  flutter_launcher_icons: "^0.14.1"

flutter_native_splash:
  color: "#D2691E"  
  image: assets/icons/my_coffeeicon.png

  android_12:
    color: "#D2691E"
    image: assets/icons/my_coffeeIcon.png

flutter_launcher_icons:
  android: "launcher_icon"      
  ios: true            
  remove_alpha_ios: true  
  image_path: "assets/icons/my_coffeeIcon.png"  
  min_sdk_android: 21  
  adaptive_icon_background: "#D2691E"  
  adaptive_icon_foreground: "assets/icons/my_coffeeIcon.png"  


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/JSON/survey.json

